project:
  type: website
  output-dir: docs
website:
  title: "My Irregular Blog"
  search: true
  navbar:
    right:
      - about.qmd
      #- index.qmd
      - others.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

